spring:
  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true